components and backend added
temirbolatov17/Kolesa-Upgrade-FE-2021 pull request #7
Opened 2021-10-26 19:26 UTC by temirbolatov17

2021-10-29 23:04 UTC, AlexPavlof requested changes
Очень круто!
Немного запутался в логике отображения/скрытия модалок и фильтрации списка товаров (тут перемудрил). Но в целом всё круто. Остальные замечания не критичные.

Кстати, на лекции не рассказывали про тег `<style>` внутри однокомпонентных файлов? Стили конкретного компонента можно хранить прям внутри компонента. Почитай, там ещё есть опция `scoped`, чтобы ограничивать видимость стилей, работает так, что в двух компонентах даже стили с одним названием не будут пересекаться.

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/user.vue
> +  name: 'user',
_Не критично_
Как правило, компоненты стараются называть с заглавной буквы. Как в имени файла, так и в поле `name`.

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/user.vue
> +  props: {
Если блок пустой, его можно не оставлять в коде

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/user.vue
> +  computed: {
Если блок пустой, его можно не оставлять в коде

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/user.vue
> +  data() {
_Не критично_
Как правило, используется определённый порядок ключей в компоненте. Негласное правило (но тем не менее оно есть в правилах для ESLint). Порядок такой: ключи, содержащие данные, необходимые для работы компонента (extends, componsnts, mixins), ключи, содержащие сами данные для отображения (props, data), вычисляемые свойства, mounted/computed (и прочие хуки), методы.

Компонент читается сверху вниз, к моменту, когда доходишь до методов, уже есть понимание, с какими данными они работают.

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/user.vue
> +      });
Всегда нужно обрабатывать исключения через catch. Иногда promise, для которого нет обработки исключения, может сломать логику всей программы.

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/user.vue
> +      });
В данном случае будет достаточно легирования в консоль.

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/tabs.vue
> +              :value="tab.value" v-model="selectedTab" checked>
Проверь, пожалуйста, но кажется когда ты выполняешь биндинг переменной через модель, то принудительное присваивание уже не нужно. То есть в `@click` в лейбле может не принимать никаких параметров, а в обработчике нужно только отправить ткущее значение из data. То есть
```javascript
sortTabs() {
    this.$emit('sorttabs', this.selectedTab);
},
```

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/search.vue
> +      search: '',
Не нашёл, где используется

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/product-card.vue
> +      @click="openCard(product)">
Если в коде ты используешь `this.product`, то в метод можно не передавать параметры

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/product-card.vue
> +      :key="product.id"
Это для чего?

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/product-card.vue
> +            product.sizes && product.sizes.length ? `Размеры ${String(product.sizes)}` : ''
Думаю, это условие лучше в `.description__hint` перенести на `v-if`

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/navigation.vue
> +  data() {
Нет данных — не должно быть и блока

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/footer.vue
> +                          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Иконки можно вынести в отдельные файлы и подключать тем же импортом

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/modal.vue
> +    data: Object,
`data` — слишком обобщённо. Давай, назовём всё же `product`

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/modal.vue
> +    openModal() {
Где используется?

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +    toggleModalWindow() {
Выглядит круто, но всё же таких методов лучше избегать. По крайней мере, если в интерфейсе не используются кнопки, которые одновременно могут делать противоположные действия.

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/modal.vue
> +    closeModal() {
Где используется?

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/modal.vue
> +  <section class="modal" v-if="isOpen">
v-if лучше вынести в родительский компонент.
Смотри, логика такая — этот компонент только отображает данные. И вызывает события для закрытия самого себя. Но вся логика отображения модального окна пусть будет в родительском компоненте.

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/components/product-card.vue
> +      :data-id="product.id"
Это для чего?

2021-10-29 23:04 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +        this.clothes = response.data;
Попробуй
```javascript
this.clothes = response.data.map((product) => {
    product.category = 'clothes';

    return product;
});
```
И для аксессуаров. В дальнейшем можно работать с данными как в прошлом уроке.

2021-10-30 12:44 UTC, temirbolatov17 commented on vue-kolesa-upgrade/src/components/tabs.vue
> +              :value="tab.value" v-model="selectedTab" checked>
Я здесь попробовал сделать как ты сказал, у меня начала возникать та проблема с которой я долго боролся)) то есть при нажатии на все товары у меня выходит одежда, при нажатии на одежду выходят аксессуары а при нажатии на аксессуары выходят все товары, пока вернул как было, не могу найти причину такого поведения(

2021-10-30 14:02 UTC, temirbolatov17 commented on vue-kolesa-upgrade/src/components/modal.vue
> +  <section class="modal" v-if="isOpen">
попробовал, но что то моя хрупкая конструкция не выдержала такого))

2021-11-02 13:31 UTC, merged